# Generated by Django 2.2.7 on 2020-01-27 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200125_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='paquetes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
