# Generated by Django 2.2.7 on 2020-01-28 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200126_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='numero',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
