# Generated by Django 2.2.7 on 2020-01-28 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movimiento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='existencias',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
